### ISSUE TITLE
MacIPgw-VM - apt repos 404.

### ISSUE THREAD

**Issue by adespoton** [zero2sixd/macipgw#10]
Not sure if the URL list needs updating, or something else is going on (like http instead of https), but the ubuntu update locations all return a 404.  Maybe the base image should update to 20.04, or switch to Debian instead of Ubuntu?

**Comment by jasonking3** [comment]
This issue is related to the VM available at macip.net.  That work is maintained separately.  I would look for support contact info at https://www.macip.net.
