### ISSUE TITLE
MacIPgw-VM - Zeroconf/Bonjour not announcing

### ISSUE THREAD

**Issue by adespoton** [zero2sixd/macipgw#11]
This is probably related to not assigning a 172.16.2.1 address, but instead using the regular assigned DHCP IPv4 address from my router, but IPv6 doesn't appear to be announcing any of the capabilities to my network, as my discovery tool doesn't pick up any from the VM, although the host system is announcing just fine.

**Comment by jasonking3** [comment]
This issue is related to the VM available at macip.net.  That work is maintained separately.  I would look for support contact info at https://www.macip.net.
