### ISSUE TITLE
macipgw: could not initialise MacIP

### ISSUE THREAD

**Issue by pgodwin** [zero2sixd/macipgw#12]
I'm attempting to get macipgw up and running on OpenWRT and am getting the following:

```
root@OpenWrt:~# macipgw -d0x111 192.168.1.0 255.255.255.0
device = tun0
macip_open: retrying in 5 seconds
macip_open: retrying in 5 seconds
macip_open: retrying in 5 seconds
macip_open: retrying in 5 seconds
macip_open: too many retries
macipgw: could not initialise MacIP
macipgw: going down on signal
Stopping

stopped.
```

Version: 
```
root@OpenWrt:~# macipgw -version
macipgw 4.0.7 - Mac IP Gateway Daemon
Copyright (c) 1997, 2013 Stefan Bethke. All rights reserved.
Copyright (c) 1988, 1992, 1993
        The Regents of the University of California.  All rights reserved.
Copyright (c) 1990, 1996 Regents of The University of Michigan.
        All Rights Reserved.
See the file COPYRIGHT for further information.
```

It could well be that I'm missing a module or component that MacIPGW depends on - but checking the code nothing jumps out at me.

**Comment by pgodwin** [comment]
Looks like it was related to atalkd not running properly.

```
> macipgw -d0x111 192.168.1.0 255.255.255.0
device = tun0
Unknown service "zip/ddp".
macipgw: could not initialise MacIP
macipgw: going down on signal
Stopping

stopped.
```
Now getting an unknown service error.

**Comment by rdmark** [comment]
An unknown service error usually means that the operating system's kernel doesn't support AppleTalk (DDP) so you may need to recompile the kernel with `appletalk` enabled.

Actually, I know for a fact that this is the case for OpenWrt. The support for AppleTalk in the OpenWrt kernel was removed in 2018, and now [brought back only a month ago](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=b2f3713801c22d496791949877e6466864eaaa41). If all goes well, upcoming stable releases will ship with AppleTalk support again.

See this discussion thread for more details: https://github.com/Netatalk/netatalk/discussions/1683

**Comment by rdmark** [comment]
As a side note: as of Netatalk 4.0 we bundle a custom version of macipgw with the netatalk package. I have ported improvements from Jason's fork, and other forks.

**Comment by pgodwin** [comment]
I'm using the upcoming build of OpenWrt with those changes, but must have missed compiling it in (though a atalkd seems to work). 
Thanks for the suggestion.

**Comment by rdmark** [comment]
If you still have issues afterwards, please do report back. If you decide to use the macipgw bundled with Netatalk, you can file a bug ticket over there.

**Comment by pgodwin** [comment]
Thanks for offer. I brought it up on OpenWRT as it may have been specific to that, and a patch has been submitted: https://forum.openwrt.org/t/dsa-and-appletalk-multicast-issues/216494/119
